### ISSUE TITLE
Bundle changes .yaml formatting

### ISSUE THREAD

**Issue by DidierLmn** [php-translation/symfony-bundle#178]
I use .yaml files for my translation files, and they are structured like this:

```
key:
    subKey: string
    subKey2: string2
```

However when editing (either via the Symfony profiler, or the WebUI) this bundle reformats all translation files of the edited locale to something like this:

```
key.subKey: string
key.subKey2: string2
```

This makes the files (in my opinion) less readable, and less easy to edit directly. Is there a way to prevent the bundle from doing this?

**Comment by bocharsky-bw** [comment]
I have a big argument in favor of inline strategy like `key.subKey` - it's easy to find in code base than expanded values. I mean, you can use "Search in files" and easily search for the entire "key.subKey" key which is impossible in your case because keys are expanded. So I like this strategy.

However, maybe some kind of configuration option can be implemented, like `translation.expand: true` to switch strategy to:

```yaml
key:
    subKey: string
    subKey2: string2
```

The question: is it worth? Because this bundle is designed to work with XLIFF format which provides some nice features like priority, notes, etc. which are impossible with YAML format

Any thoughts?

**Comment by Nyholm** [comment]
My take on it is that the translation files is just a cache. And you should not be bothered with the file format or syntax of your cache files.

**Comment by DidierLmn** [comment]
Maybe you're right, maybe I've thinking too much from my own perspective instead of that of a translator/user. 

Since there currently isn't a feature like this, I'll try to work with it as is, or try switching to XLIFF. 
Thanks for the comments/suggestions.

**Comment by bocharsky-bw** [comment]
I'd recommend you to use any UI you like: http://php-translation.readthedocs.io/en/latest/symfony/index.html#features - and use the power of XLIFF 👍

**Comment by Nyholm** [comment]
Closing this since it is solved. 

If you have more questions, feel free to reopen or create a new issue.
