### ISSUE TITLE
Use "desc" as default translation just for default locale

### ISSUE THREAD

**Issue by RonaldEAM** [php-translation/symfony-bundle#223]
When extracting for multiple languages they all get "desc", that is written in default locale, as target translation and in Web UI (and I suppose other tools as well) we see that all languages are in 100% progress and it's a problem for translators to know what is not properly translated if we have a lot of messages, is not ok.

**Propose:**
Use "desc" as default translation just for default locale, for example if default locale is `en` then only `*.en.xlf` files will get "desc" as target translations, and files like `*.es.xlf`, `*.pt.xlf`, etc will have target translation empty

**Comment by Nyholm** [comment]
Thank you for this issue. I'll see if I can find a good solution

**Comment by Nyholm** [comment]
Could you test #243?

**Comment by Nils-1st-retail** [comment]
Hi,
it seems that the code introduced to only use the desc and translation for the default locale contains a bug.

In /symfony-bundle/Service/Importer.php  on line 113 you have added a check to the current locate is the same as the default locale

The problem is that && is resolved before the assignment of $meta->getDesc() to $newTranslation. 
This causes $newTranslation to become a boolean instead of the text. Causing the default translation to be 1 or 0.

The problem can be seen by running this little test code

var_dump(null !== $newTranslation = "testing" && "en" === "en");
var_dump($newTranslation);
var_dump((null !== $newTranslation = "testing") && "en" === "en");
var_dump($newTranslation);

Which returns 

bool(true)
bool(true)
bool(true)
string(7) "testing"

The solution is to wrap 
`null !== $newTranslation = $meta->getDesc()`
In a set of parenthesis to force the intended order of opperations
