### ISSUE TITLE
Bundle's Debug Translation page is not in sync with Symfony's anymore

### ISSUE THREAD

**Issue by bocharsky-bw** [php-translation/symfony-bundle#295]
As you can see some elements are missing.

Bundle's Debug Translation page:
<img width="1440" alt="Screen Shot 2019-03-13 at 17 02 32" src="https://user-images.githubusercontent.com/3317635/54289452-e0874480-45b1-11e9-8278-a6652faff1eb.png">

Symfony's Debug Translation page:
<img width="1440" alt="Screen Shot 2019-03-13 at 17 02 12" src="https://user-images.githubusercontent.com/3317635/54289470-e7ae5280-45b1-11e9-86df-43713991ff74.png">

**Comment by rvanlaak** [comment]
Maybe we can enhance the default translator's profiler Twig file by wrapping several elements in blocks over there. That would make it easier to keep it in sync for this bundle:

```twig
{% block translationRow %}
    {{ parent() }}
	<td> edit | sync </td>
{% endblock %}

**Comment by bocharsky-bw** [comment]
Yeah, great idea 👍

**Comment by rvanlaak** [comment]
The related file: https://github.com/symfony/web-profiler-bundle/blob/master/Resources/views/Collector/translation.html.twig

Any idea how the `render_table` macro can get "extended"? I'm not sure if it is possible to put extendable blocks in a macro, so that would make adding several optional parameters the only option.

Did create https://github.com/symfony/web-profiler-bundle/pull/14 for the metrics

**Comment by rvanlaak** [comment]
@bocharsky-bw maybe you can provide your input at https://github.com/symfony/symfony/pull/30560

**Comment by bocharsky-bw** [comment]
@rvanlaak Yeah, that's a tough question! Hm, I don't see another solution except for adding a few optional args to the macro :/ Maybe split that one macro in a few macros?.. not sure if it will solve the problem, just thinking out loud, but it sounds like not an elegant solution. Well, probably we could add those extra buttons/checkboxes via JS? What do you think?
