### ISSUE TITLE
Move Translation\Bundle\EditInPlace\Translator

### ISSUE THREAD

**Issue by Nyholm** [php-translation/symfony-bundle#44]
The "EditInPlace translator" should be living under `Translation\Bundle\Translator`, right?

Same would go for ResponseListener and Twig. Or do we like to keep all these classes in the "feature folder"? What do you thing?

**Comment by damienalexandre** [comment]
Even if it make sense to move the https://github.com/php-translation/symfony-bundle/blob/master/EditInPlace/Translator.php class to `Translation\Bundle\Translator` because, well, it's a Translator,
having everything in the feature folder is also convenient, and the mentioned class is not reusable anyway from my POV...

I'm not against it, let's try to be consistent with the other features of the Bundle :+1:

**Comment by Nyholm** [comment]
Yeah. 👍  for consistency. 

I do not think any of our classes are reusable. The reusable stuff are in other repositories. 
Other features are "spread out" in the bundle and some of the EditInPlace features are too. Like the controller and resources.
