### ISSUE TITLE
[EditInPlace] Disable "can't be translated" for specific items

### ISSUE THREAD

**Issue by rvanlaak** [php-translation/symfony-bundle#66]
The "can't be edited" message is great, but it breaks behavior in some cases. Some enhancements for this message would be:

* option to disable it completely, and show the original translation
* option to exclude specific items from "edit in place" (maybe via optional data in `xliff`?)

We can always refer to the web UI or profiler.

**Comment by damienalexandre** [comment]
Could you provide an example of broken behavior? 

This message is done by post-processing the response content, because there is no way to tell from a `|trans` call in twig if we are in an acceptable HTML tag / attribute... 

Maybe showing the original translation is possible,
but exclusion sound hard to implement without hacks / translation key name convention...

**Comment by rvanlaak** [comment]
We use Twig to do some javascript translations. For example our logout button - shown at every page - has a `sweetAlert` confirm dialog. As it isn't translatable, it adds the "can't translate" label, which leads to a broken dialog.

**Comment by rvanlaak** [comment]
Would even be better to disable the "can't be translated" message. For us it would be obvious that it can't be translated when there is no highlight (as with other dynamic data).

**Comment by rvanlaak** [comment]
This is resolved via #89
