### ISSUE TITLE
AutoAdder for translations does not invalidate cache

### ISSUE THREAD

**Issue by prolic** [php-translation/symfony-bundle#74]
`%kernel.cache_dir%/translations` is still there after translations are added, resulting in adding translations to remote storage again and again, unless the cache is manually cleared.

**Comment by damienalexandre** [comment]
Thanks for the report!

@Nyholm we could reuse code from here: https://github.com/php-translation/symfony-bundle/blob/master/Controller/EditInPlaceController.php#L58 - this needs to be handled globally in the bundle.

**Comment by Nyholm** [comment]
@prolic: Am I correct that you are only experiencing this with env:prod? In env:dev  we should not have any issues with cache.

**Comment by prolic** [comment]
No, it's in dev-mode. Also the same problem comes up, when I edit a translation in the symfony profiler. I need to clear the cache manually to make the change visibile.

**Comment by prolic** [comment]
Also, is this feature meant to be disabled in production?

**Comment by Nyholm** [comment]
No, Im just trying to understand the problem.

**Comment by toooni** [comment]
@Nyholm @prolic can't reproduce the issue. Auto-Adding seems to work fine. Can anybody with permissions close the issue?

**Comment by Nyholm** [comment]
👍 
Thank you for trying to reproduce this. I will try to reproduce it myself tomorrow to see if it can be closed.

**Comment by toooni** [comment]
@Nyholm fyi: @prolic implemented the solution in our application.

**Comment by toooni** [comment]
@Nyholm I think I found the problem. The cache isn't the issue here - it's the local storage. In our case we have country specific translations with locales like `de_CH` and fallback like `de`. It can happen that for a specific domain `messages` we do have a file like `messages.de.xlf` but no file `messages.de_CH.xlf`, because there was no need for a country specific translation in this domain yet. Now the AutoAdder does not seem to create a new file `messages.de_CH.xlf` if it doesn't exist.

The profiler problem from @prolic happened because the phrase-app adapter created the new translations on remote. On a second request the translation still didn't exist on local storage (because of the storage problem) but already existed on remote (first request). The phrase-app adapter isn't yet able to handle that correct (I'll make a PR today).

**Comment by toooni** [comment]
https://github.com/php-translation/phraseapp-adapter/pull/6 prevents the profiler to fail if translation already exists on remote storage.

**Comment by toooni** [comment]
@Nyholm I was digging a bit more and I've seen that the symfony-storage isn't very flexible because it's based on local translation files. It doesn't know anything about how to save a new file because it iterates only through existing files.

I have some ideas how this could be solved:
- When there is no match inside `writeCatalogue` in `FileStorage`, it tries to make a fallback to match a file without the locale `preg_match('|/'.$domain.'\(a-zA-Z_)\.([a-z]+)$|', $path, $matches)` and uses this one. (There's still a problem if there are no files at all for a specific domain)
- Adding a configuration `default_output_format` which is being injected into the symfony-storage service. It seems that this is only thing missing for `writeCatalogue` to create new files (as far as I understood)
- Throwing an Exception if no file was matched to inform the user that he has to create the file by himself.
- Do nothing (Maybe this was already your intention?) and leave it to the user to ensure that he creates a new file when adding new locales or domains.

A combination of these might also be possible: Make `default_output_format` optional and throw an exception if no format is defined and no existing (matching) file has been found.

**Comment by Nyholm** [comment]
Thank you @toooni. Your investigation and suggestions were really helpful. I added a `default_output_format` option and will write a new file to the first configured dir.
